export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const SET_CURRENT_PAGE_NEWS = 'SET_CURRENT_PAGE_NEWS';
export const SET_CURRENT_PAGE_PODCAST = 'SET_CURRENT_PAGE_PODCAST';

// export const FETCH_NEWS_START = 'FETCH_NEWS_START';
// export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
// export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

// export const FETCH_PODCAST_START = 'FETCH_PODCAST_START';
// export const FETCH_PODCAST_SUCCESS = 'FETCH_PODCAST_SUCCESS';
// export const FETCH_PODCAST_FAILED = 'FETCH_PODCAST_FAILED';