export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILED = 'FETCH_NEWS_FAILED';

export const FETCH_PODCAST_START = 'FETCH_PODCAST_START';
export const FETCH_PODCAST_SUCCESS = 'FETCH_PODCAST_SUCCESS';
export const FETCH_PODCAST_FAILED = 'FETCH_PODCAST_FAILED';